### PR TITLE
chore: update covenant to 2.1 and correct contact

### PR DESCRIPTION
**Pull request by ecrupper**
New version is available with the [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).

Also the email for reporting needs to be updated.

Upon the approval of this PR, I will update the Code of Conduct for all our repos. I figured this would be a good first repo for any discussion/suggestions if there is any.

### CODE REVIEW

**Review by kaymckay — APPROVED** [review]
lgtm - are you going to change for every repo?

**Comment by kneal** [comment]
Is this a file we can just depend on the parent `.github` repository for?
https://github.com/go-vela/.github

It would save the headache of having to update every repository.

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Comment by bmuenzenmeyer** [comment]
I've reached out directly to Legal to enquire about the status of this. My intent is to propagate the change across the org.

edit: Legal is looking into it

**Comment by bmuenzenmeyer** [comment]
Update: This cleared Legal review but is being quick run through Ethics

**Comment by bmuenzenmeyer** [comment]
Update: This now has a full green light. 🟢 

In the coming days I'll be propagating the change to the main org - but for now feel free to advance this here or as @kneal mentioned, updating https://github.com/go-vela/.github and cleaning up the other repos is sufficient

**Comment by wass3r** [comment]
@bmuenzenmeyer thanks for the update! ❤️ 

@kneal agreed. let's move it to `go-vela/.github` repo. of course, that also means, we have to delete the previous version from each repo because they will take precedence until it's removed.

**Review by plyr4 — APPROVED** [review]

**Comment by wass3r** [comment]
closing this in favor of https://github.com/go-vela/.github/pull/8

**Pull request closed without merging**
