### PR TITLE
fix: remove old docs

### PR DESCRIPTION
**Pull request by kneal**
This PR removes the documentation that moved to a new location:
https://go-vela.github.io/docs/concepts/pipeline/steps/ruleset/

### CODE REVIEW

**Review by jbrockopp — APPROVED** [review]
LGTM

**Review by wass3r — COMMENTED** [review]
FYI.. information on `continue` which was on the page this is removing doesn't exist on the new page.

**Comment by kneal** [comment]
@wass3r I will add a new PR for adding those docs back to the site.

**Comment by wass3r** [comment]
ok, thanks!

**Review by wass3r — APPROVED** [review]

**Pull request merged**
