### PR TITLE
refactor: use auto-generated docs for commands

### PR DESCRIPTION
**Pull request by kneal**
This PR will delete the existing CLI docs in favor of using auto-generated formatted commands.

### CODE REVIEW

**Review by jbrockopp — CHANGES_REQUESTED** [review]
Is there any concern for the disparity in this change and what we have now?

I wouldn't recommend doing this until the generated docs offer more content.

**Comment by kneal** [comment]
Which missing content are you concerned about?

The reason I ask, I can move content into the CLI `Description` and `Usage` details per command and category to make up for the lack of current content on generation. I just need to know what specifically people would like to see.

**Comment by jbrockopp** [comment]
@kneal TBH, I'm not entirely sure what content our users actually like from the CLI docs today.

What I'll do is provide a sample of what I'm seeing and then we can determine what we want and don't want.

## Setup

I checked out the `refactor/ref/commands` branch locally and then ran `hugo serve`.

I was able to navigate to http://localhost:1313/docs/reference/cli/commands/ which is the generated doc we're importing.

## Focus

For the sake of conversation, I'll focus on `vela get build` as the example.

Here is what we have today:

https://go-vela.github.io/docs/reference/cli/build/get/

And here is what this PR proposes:

http://localhost:1313/docs/reference/cli/commands/#build-builds

Here is the screen capture of what I'm seeing:

image

## Differences

* [Offer a syntax example of how to run](https://go-vela.github.io/docs/reference/cli/build/get/#command) the `vela get build` command.
* Under that same syntax example is a tip instructing users to run `vela get build --help` for more information
* The [parameters are ordered in a table format](https://go-vela.github.io/docs/reference/cli/build/get/#parameters)
* The [parameters provide the environment variables you can configure to set them](https://go-vela.github.io/docs/reference/cli/build/get/#parameters)
* [Offer a sample request and response](https://go-vela.github.io/docs/reference/cli/build/get/#sample) for the `vela get build` command
* References to using the `config` file for setting values for the command

FWIW:

I'm unsure if we want any of these or not from the original document.. There are things I noticed that are different.

**Comment by kneal** [comment]
I am aware of the differences, so that feedback is not super useful.  When I asked:
> Which missing content are you concerned about?

I was looking more to identify what you like about the current docs. That identification would help me understand what content should be migrated to be native in the CLI docs so it gets rendered in the auto-generated documentation. For example, if you said you liked the [samples](https://go-vela.github.io/docs/reference/cli/build/get/#sample) I would have said I can move examples:

```EXAMPLES:
  1. Get builds for a repository.
    $ vela get build --org MyOrg --repo MyRepo
  2. Get builds for a repository with wide view output.
    $ vela get build --org MyOrg --repo MyRepo --output wide
  3. Get builds for a repository with yaml output.
    $ vela get build --org MyOrg --repo MyRepo --output yaml
  4. Get builds for a repository with json output.
    $ vela get build --org MyOrg --repo MyRepo --output json
  5. Get builds for a repository when config or environment variables are set.
    $ vela get build
```
  
To a new location within the `--help` command so they are visible in the auto-generated format. 

This new pattern of auto-generation is not going to be 1on1. But, if we can cherry-pick what we think is valuable. They can be potentially re-formatted into the `--help` docs so they appear in both locations. If you like the existing format of the docs and believe it is more user friendly then I will just close this PR and move on to a new section of the docs to revise.

**Comment by kneal** [comment]
Closing this for now because of lack of appetite

**Pull request closed without merging**
