### PR TITLE
 feat: add docs for pipeline validation

### PR DESCRIPTION
**Pull request by kneal**

### CODE REVIEW

**Review by jbrockopp — DISMISSED** [review]
LGTM

**Comment by wass3r** [comment]
we might want to put this into draft mode until https://github.com/go-vela/cli/pull/248 is merged.

**Review by KellyMerrick — DISMISSED** [review]
lgtm

correction: found a small mistake and will submit a fix momentarily

**Review by wass3r — APPROVED** [review]

**Comment by wass3r** [comment]
i think this is good to go as soon as we cut a release on CLI 👍🏼

**Review by meinenec — APPROVED** [review]

**Pull request merged**
