### PR TITLE
remove redundant files

### PR DESCRIPTION
**Pull request by wass3r**
we are not really using package*.json as we re-install newer, ephemeral versions in the workflow on each run. deploy.sh is not used at all either. the vue js dependency from the package.json in the root looks to be superfluous as well as we hardcode the script reference inline to load VueJS.

tested this out locally by following current pipeline and works out well.

### CODE REVIEW

**Comment by kneal** [comment]
Will the submodule just re-add these files?

**Review by jbrockopp — APPROVED** [review]
LGTM

**Comment by wass3r** [comment]
@kneal if it was a true submodule, yes :P

**Review by kneal — APPROVED** [review]
Ah thanks!

**Pull request merged**
