### PR TITLE
refactor(usage): update usage to be focused on using vela concepts

### PR DESCRIPTION
**Pull request by kneal**
Migrated Content Changes

* All pipeline usage examples are being collapsed into their proper concept documentation.

New Content Changes:

* Examples renamed to Samples for consistency
* Samples is becoming a first-class citizen and will be the core of usage
* Added samples for both steps and stages pipelines
* Samples link back to their appropriate concept documentation used in the sample pipeline

### CODE REVIEW

**Comment by wass3r** [comment]
probably hold on the PR until release?

**Comment by kneal** [comment]
This can go in right away. It’s prep for new 0.5.0 content

**Review by wass3r — DISMISSED** [review]

**Review by jbrockopp — DISMISSED** [review]
LGTM

**Review by plyr4 — APPROVED** [review]

**Review by jbrockopp — APPROVED** [review]
LGTM

**Pull request merged**
