### PR TITLE
feat(api): adding pipeline endpoints

### PR DESCRIPTION
**Pull request by plyr4**
coincides with 
https://github.com/go-vela/server/pull/203

in Draft until https://github.com/go-vela/community/milestone/2 is release

### CODE REVIEW

**Review by KellyMerrick — DISMISSED** [review]
lgtm

**Review by jbrockopp — CHANGES_REQUESTED** [review]
I know we don't want to merge this until https://github.com/go-vela/server/pull/203 is complete 👍 

But, do we want to merge this before we actually cut a release for [go-vela/server](https://github.com/go-vela/server)?

I'm asking because if we do decide to merge this after https://github.com/go-vela/server/pull/203 is merged, I could see customers getting confused about what we have documented.

Mainly, they wouldn't be able to access any of these endpoints until we released internally.

Thoughts?

**Comment by plyr4** [comment]
Good call @jbrockopp I will convert this to a draft to block merging before we can cut a release with the endpoints when go-vela/server#203 is complete 👍

**Review by jbrockopp — DISMISSED** [review]
LGTM

**Review by jbrockopp — APPROVED** [review]
LGTM

**Review by wass3r — APPROVED** [review]

**Pull request merged**
