### PR TITLE
chore(reference): add VELA_SOURCE_WEBHOOK_ADDR

### PR DESCRIPTION
**Pull request by KellyMerrick**
Documentation for https://github.com/go-vela/server/pull/485.

### CODE REVIEW

**Review by plyr4 — APPROVED** [review]

**Review by kneal — APPROVED** [review]
LGTM 🐬

**Review by wass3r — APPROVED** [review]

**Review by jbrockopp — CHANGES_REQUESTED** [review]
Is this valid? I thought the variable name changed to `VELA_SCM_WEBHOOK_ADDR`:

https://github.com/go-vela/server/blob/master/scm/flags.go#L62-L71

https://go-vela.github.io/docs/administration/server/reference/#vela_scm_webhook_addr

IIRC, `VELA_SOURCE_WEBHOOK_ADDR` was left for backwards compatible reasons:

https://github.com/go-vela/server/pull/536

**Comment by KellyMerrick** [comment]
@jbrockopp thanks for pointing that out. Looks like it was already documented, so I'll close this pr.

**Comment by jbrockopp** [comment]
@KellyMerrick do you have interest in creating a new PR or modifying this one to update the description? 👍 

Thinking that some of the details you have here are valuable for the `VELA_SCM_WEBHOOK_ADDR` description?

> Use this when the Vela server address that the source provider can send webhooks to differs from the server address the UI and oauth flows use, such as when the server is behind a Firewall or NAT.

**Pull request closed without merging**
