### PR TITLE
Implementing site indexing and static site search 

### PR DESCRIPTION
**Pull request by plyr4**
Using Hugo to index the site into a JSON file, then Vue.js components to filter and search across the JSON ultra fast to get a dropdown of pages that contain your search query in their title, content, or link.

### CODE REVIEW

**Comment by plyr4** [comment]
See [demo video](https://target-tts.slack.com/archives/GCREYBM41/p1573329088211700?thread_ts=1573329017.211400&cid=GCREYBM41) in Target TTS Slack

**Comment by plyr4** [comment]
could clean up the <script> by moving into its own .js file and abstracting the repetitive code, but was running into issues with Hugo seeing files in the docsy theme directories.

**Comment by kneal** [comment]
LGTM 🐬

**Review by wass3r — APPROVED** [review]
LGTM

**Pull request merged**
